spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/test?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: socialnetwok2021@gmail.com
    password: sizadrhjufeacfpw
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
server:
  port: 8086
  servlet:
    contextPath: /api/v1

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    root: INFO
    skillbox: TRACE

cloudinary:
  url: cloudinary://889892999924949:HBEMk4_4zYqvw8Eg6e2vwqDQxy4@dmw3gspng

front:
  host: http://localhost:8084